-- Cleansed DimCustomer --
SELECT [CustomerKey]
      --,[GeographyKey]
      --,[CustomerAlternateKey]
      --,[Title]
      ,[FirstName]
      --,[MiddleName]
      ,[LastName]
	  ,([FirstName] + ' ' +[LastName]) AS [FullName] 
      --,[NameStyle]
      --,[BirthDate]
      ,[MaritalStatus]
      --,[Suffix]
      ,[Gender]
      --,[EmailAddress]
      ,[YearlyIncome]
      --,[TotalChildren]
      --,[NumberChildrenAtHome]
      --,[EnglishEducation]
      --,[SpanishEducation]
      --,[FrenchEducation]
      --,[EnglishOccupation]
      --,[SpanishOccupation]
      --,[FrenchOccupation]
      --,[HouseOwnerFlag]
      --,[NumberCarsOwned]
      --,[AddressLine1]
      --,[AddressLine2]
      --,[Phone]
      --,[DateFirstPurchase]
      --,[CommuteDistance]
	  ,g.[City] AS CustomerCity
  FROM [AdventureWorksDW2022].[dbo].[DimCustomer] AS c
  LEFT JOIN DimGeography AS g
	ON g.GeographyKey = c.GeographyKey
